name: 'Builds and Test'
description: 'Builds the library and runs the unit tests'

runs:
  using: composite

  steps:

    - name: Restore Packages
      shell: bash
      run: dotnet restore

    - name: Build Solution
      shell: bash
      run: dotnet build --no-restore

    - name: Run Unit Tests
      shell: bash
      run: dotnet test --no-build