name: publish

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Build and Push package
        if: contains(github.ref, 'tags')
        run: |
          dotnet restore
          $VERSION =  $("${{github.ref}}" -split "/")[-1].Substring(1)
          dotnet pack --configuration Release --output ./pack /p:PackageVersion=$VERSION
          dotnet nuget push ./pack/wimm.Secundatives.$VERSION.nupkg -s https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }}
        shell: pwsh
