name: Release Please

on:
  push:
    branches: [master]

jobs:
  build-and-test:
    uses: wareismymind/secundatives/.github/workflows/build-and-test.yml@master

  release-please:
    name: Run Release Please
    needs: [build-and-test]
    runs-on: ubuntu-latest

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Setup Release Please
        uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          package-name: secundatives

      - name: Set Release Info
        if: ${{ steps.release.outputs.release_created }}
        id: version
        env:
          VERSION: "${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"
        run: echo "::set-output name=version::${VERSION}"

  release-package:
    name: Release Package
    runs-on: ubuntu-latest
    needs: [release-please]
    if: ${{ needs.release-please.outputs.release_created }}
    env:
      VERSION: ${{ needs.release-please.outputs.version }}
      NUGET_SOURCE: https://api.nuget.org/v3/index.json
      NUGET_API_KEY: ${{ secrets.NUGET_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: false

      - name: Dotnet Restore
        run: dotnet restore

      - name: Dotnet Build
        run: dotnet build --no-restore -c Release /p:Version=$VERSION

      - name: Dotnet Pack
        run: dotnet pack --no-build -c Release /p:Version=$VERSION

      - name: Dotnet NuGet Push
        run: dotnet nuget push --source "$NUGET_SOURCE" --api-key "$NUGET_API_KEY" ./pack/*
